In [1]:
%pylab inline
import pandas as pd
import seaborn as sns
import plotly.express as px
import statsmodels.api as sm
import math
import os
import time
import datetime
from datetime import datetime
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn import metrics
import statsmodels.formula.api as sm

Populating the interactive namespace from numpy and matplotlib


In [2]:
data_train=pd.read_csv('C:/Users/Bhumihar Rakesh/Desktop/Python/Kaggle/COVID-19 Week 4/train.csv',header=0)
data_test=pd.read_csv('C:/Users/Bhumihar Rakesh/Desktop/Python/Kaggle/COVID-19 Week 4/test.csv',header=0)


In [3]:
data_train

Id Province_State Country_Region        Date  ConfirmedCases  \
0          1            NaN    Afghanistan  22-01-2020               0   
1          2            NaN    Afghanistan  23-01-2020               0   
2          3            NaN    Afghanistan  24-01-2020               0   
3          4            NaN    Afghanistan  25-01-2020               0   
4          5            NaN    Afghanistan  26-01-2020               0   
...      ...            ...            ...         ...             ...   
25035  35644            NaN       Zimbabwe  06-04-2020              10   
25036  35645            NaN       Zimbabwe  07-04-2020              11   
25037  35646            NaN       Zimbabwe  08-04-2020              11   
25038  35647            NaN       Zimbabwe  09-04-2020              11   
25039  35648            NaN       Zimbabwe  10-04-2020              13   

       Fatalities  
0               0  
1               0  
2               0  
3               0  
4               0  
...           ...  
25035           1  
25036           2  
25037           3  
25038           3  
25039           3  

[25040 rows x 6 columns]

In [4]:
data_test

ForecastId Province_State Country_Region        Date
0               1            NaN    Afghanistan  2020-04-02
1               2            NaN    Afghanistan  2020-04-03
2               3            NaN    Afghanistan  2020-04-04
3               4            NaN    Afghanistan  2020-04-05
4               5            NaN    Afghanistan  2020-04-06
...           ...            ...            ...         ...
13454       13455            NaN       Zimbabwe  2020-05-10
13455       13456            NaN       Zimbabwe  2020-05-11
13456       13457            NaN       Zimbabwe  2020-05-12
13457       13458            NaN       Zimbabwe  2020-05-13
13458       13459            NaN       Zimbabwe  2020-05-14

[13459 rows x 4 columns]

In [5]:
data_train.shape

(25040, 6)

In [6]:
data_test.shape

(13459, 4)

In [7]:
data_train.dtypes

Id                 int64
Province_State    object
Country_Region    object
Date              object
ConfirmedCases     int64
Fatalities         int64
dtype: object

In [8]:
data_test.dtypes

ForecastId         int64
Province_State    object
Country_Region    object
Date              object
dtype: object

In [9]:
data_train.info() , data_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25040 entries, 0 to 25039
Data columns (total 6 columns):
Id                25040 non-null int64
Province_State    10640 non-null object
Country_Region    25040 non-null object
Date              25040 non-null object
ConfirmedCases    25040 non-null int64
Fatalities        25040 non-null int64
dtypes: int64(3), object(3)
memory usage: 1.1+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13459 entries, 0 to 13458
Data columns (total 4 columns):
ForecastId        13459 non-null int64
Province_State    5719 non-null object
Country_Region    13459 non-null object
Date              13459 non-null object
dtypes: int64(1), object(3)
memory usage: 420.7+ KB


(None, None)

In [10]:
data_train

Id Province_State Country_Region        Date  ConfirmedCases  \
0          1            NaN    Afghanistan  22-01-2020               0   
1          2            NaN    Afghanistan  23-01-2020               0   
2          3            NaN    Afghanistan  24-01-2020               0   
3          4            NaN    Afghanistan  25-01-2020               0   
4          5            NaN    Afghanistan  26-01-2020               0   
...      ...            ...            ...         ...             ...   
25035  35644            NaN       Zimbabwe  06-04-2020              10   
25036  35645            NaN       Zimbabwe  07-04-2020              11   
25037  35646            NaN       Zimbabwe  08-04-2020              11   
25038  35647            NaN       Zimbabwe  09-04-2020              11   
25039  35648            NaN       Zimbabwe  10-04-2020              13   

       Fatalities  
0               0  
1               0  
2               0  
3               0  
4               0  
...           ...  
25035           1  
25036           2  
25037           3  
25038           3  
25039           3  

[25040 rows x 6 columns]

In [11]:
data_train['Date'] = pd.to_datetime(data_train['Date'], infer_datetime_format=True)
data_test['Date']=pd.to_datetime(data_test['Date'],infer_datetime_format=True)

In [12]:
data_train.dtypes

Id                         int64
Province_State            object
Country_Region            object
Date              datetime64[ns]
ConfirmedCases             int64
Fatalities                 int64
dtype: object

In [13]:
data_test.dtypes

ForecastId                 int64
Province_State            object
Country_Region            object
Date              datetime64[ns]
dtype: object

In [14]:
data_train.loc[:,'Date']=data_train.Date.dt.strftime("%m%d")
data_train['Date']=data_train['Date'].astype(int)

In [15]:
data_train.dtypes

Id                 int64
Province_State    object
Country_Region    object
Date               int32
ConfirmedCases     int64
Fatalities         int64
dtype: object

In [16]:
data_test.loc[:,'Date']=data_test.Date.dt.strftime("%m%d")
data_test['Date']=data_test['Date'].astype(int)

In [17]:
data_test.dtypes

ForecastId         int64
Province_State    object
Country_Region    object
Date               int32
dtype: object

In [18]:
data_train

Id Province_State Country_Region  Date  ConfirmedCases  Fatalities
0          1            NaN    Afghanistan   122               0           0
1          2            NaN    Afghanistan   123               0           0
2          3            NaN    Afghanistan   124               0           0
3          4            NaN    Afghanistan   125               0           0
4          5            NaN    Afghanistan   126               0           0
...      ...            ...            ...   ...             ...         ...
25035  35644            NaN       Zimbabwe   406              10           1
25036  35645            NaN       Zimbabwe   407              11           2
25037  35646            NaN       Zimbabwe   408              11           3
25038  35647            NaN       Zimbabwe   409              11           3
25039  35648            NaN       Zimbabwe   410              13           3

[25040 rows x 6 columns]

In [19]:
data_train.Province_State.fillna('NA',inplace=True)


In [20]:
data_test.Province_State.fillna('NA',inplace=True)

In [21]:
data_train

Id Province_State Country_Region  Date  ConfirmedCases  Fatalities
0          1             NA    Afghanistan   122               0           0
1          2             NA    Afghanistan   123               0           0
2          3             NA    Afghanistan   124               0           0
3          4             NA    Afghanistan   125               0           0
4          5             NA    Afghanistan   126               0           0
...      ...            ...            ...   ...             ...         ...
25035  35644             NA       Zimbabwe   406              10           1
25036  35645             NA       Zimbabwe   407              11           2
25037  35646             NA       Zimbabwe   408              11           3
25038  35647             NA       Zimbabwe   409              11           3
25039  35648             NA       Zimbabwe   410              13           3

[25040 rows x 6 columns]

In [22]:
data_test

ForecastId Province_State Country_Region  Date
0               1             NA    Afghanistan   402
1               2             NA    Afghanistan   403
2               3             NA    Afghanistan   404
3               4             NA    Afghanistan   405
4               5             NA    Afghanistan   406
...           ...            ...            ...   ...
13454       13455             NA       Zimbabwe   510
13455       13456             NA       Zimbabwe   511
13456       13457             NA       Zimbabwe   512
13457       13458             NA       Zimbabwe   513
13458       13459             NA       Zimbabwe   514

[13459 rows x 4 columns]

In [23]:
#data1 = data_train.groupby(['Country_Region','Province_State','Date'])['ConfirmedCases'].sum() \
#                          .groupby(['Country_Region','Province_State']).max().sort_values() \
#                          .groupby(['Country_Region']).sum().sort_values(ascending = False)

#top15 = pd.DataFrame(data1).head(15)
#top15

In [24]:
data_train.isna().sum()

Id                0
Province_State    0
Country_Region    0
Date              0
ConfirmedCases    0
Fatalities        0
dtype: int64

In [25]:
data_test.isna().sum()

ForecastId        0
Province_State    0
Country_Region    0
Date              0
dtype: int64

In [26]:
def unique(data_train): 
    x = np.array(data_train['Country_Region']) 
    print(np.unique(x))

In [27]:
unique(data_train)

['Afghanistan' 'Albania' 'Algeria' 'Andorra' 'Angola'
 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Australia' 'Austria'
 'Azerbaijan' 'Bahamas' 'Bahrain' 'Bangladesh' 'Barbados' 'Belarus'
 'Belgium' 'Belize' 'Benin' 'Bhutan' 'Bolivia' 'Bosnia and Herzegovina'
 'Botswana' 'Brazil' 'Brunei' 'Bulgaria' 'Burkina Faso' 'Burma' 'Burundi'
 'Cabo Verde' 'Cambodia' 'Cameroon' 'Canada' 'Central African Republic'
 'Chad' 'Chile' 'China' 'Colombia' 'Congo (Brazzaville)'
 'Congo (Kinshasa)' 'Costa Rica' "Cote d'Ivoire" 'Croatia' 'Cuba' 'Cyprus'
 'Czechia' 'Denmark' 'Diamond Princess' 'Djibouti' 'Dominica'
 'Dominican Republic' 'Ecuador' 'Egypt' 'El Salvador' 'Equatorial Guinea'
 'Eritrea' 'Estonia' 'Eswatini' 'Ethiopia' 'Fiji' 'Finland' 'France'
 'Gabon' 'Gambia' 'Georgia' 'Germany' 'Ghana' 'Greece' 'Grenada'
 'Guatemala' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti' 'Holy See'
 'Honduras' 'Hungary' 'Iceland' 'India' 'Indonesia' 'Iran' 'Iraq'
 'Ireland' 'Israel' 'Italy' 'Jamaica' 'Japan' 'Jordan' 'Kaz

In [28]:
data_train['Country_Region'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Brunei', 'Bulgaria', 'Burkina Faso', 'Burma', 'Burundi',
       'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada',
       'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
       'Congo (Brazzaville)', 'Congo (Kinshasa)', 'Costa Rica',
       "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czechia', 'Denmark',
       'Diamond Princess', 'Djibouti', 'Dominica', 'Dominican Republic',
       'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea',
       'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France',
       'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece',
       'Grenada', 'Guatemala', 'Guinea', 'Guine

In [29]:
from sklearn import preprocessing

In [30]:
label_encoder = preprocessing.LabelEncoder()

In [31]:
data_train['Country_Region']= label_encoder.fit_transform(data_train['Country_Region'])

In [32]:
data_train['Province_State'] = label_encoder.fit_transform(data_train['Province_State'])

In [33]:

data_test['Country_Region']= label_encoder.fit_transform(data_test['Country_Region'])

In [34]:
data_test['Province_State'] = label_encoder.fit_transform(data_test['Province_State'])

In [35]:
data_train['Country_Region'].unique()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [36]:
data_test['Country_Region'].unique()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [37]:
data_train['Province_State'].unique()

array([ 72,   8,  80,  86,  98, 110, 114, 122, 127,   2,  12,  61,  75,
        82,  87,  88,  91,  94,  97, 103, 131,   4,   9,  17,  28,  29,
        35,  36,  37,  38,  40,  41,  42,  43,  44,  45,  49,  52,  53,
        54,  57,  59,  83,  96, 104, 105, 106, 107, 108, 117, 118, 130,
       132, 133,  24,  32,  26,  27,  33,  62,  65,  76,  99, 101, 102,
       113,   7,  11,  20, 109,   0,   1,   5,   6,  14,  18,  19,  21,
        22,  25,  30,  34,  39,  46,  47,  48,  50,  55,  56,  58,  60,
        63,  64,  66,  67,  68,  69,  70,  73,  74,  77,  78,  79,  81,
        84,  85,  89,  90,  92,  93,  95, 100, 111, 112, 115, 116, 120,
       121, 123, 124, 125, 126, 128, 129,   3,  10,  13,  15,  16,  23,
        31,  51,  71, 119], dtype=int64)

In [38]:
data_test['Province_State'].unique()

array([ 72,   8,  80,  86,  98, 110, 114, 122, 127,   2,  12,  61,  75,
        82,  87,  88,  91,  94,  97, 103, 131,   4,   9,  17,  28,  29,
        35,  36,  37,  38,  40,  41,  42,  43,  44,  45,  49,  52,  53,
        54,  57,  59,  83,  96, 104, 105, 106, 107, 108, 117, 118, 130,
       132, 133,  24,  32,  26,  27,  33,  62,  65,  76,  99, 101, 102,
       113,   7,  11,  20, 109,   0,   1,   5,   6,  14,  18,  19,  21,
        22,  25,  30,  34,  39,  46,  47,  48,  50,  55,  56,  58,  60,
        63,  64,  66,  67,  68,  69,  70,  73,  74,  77,  78,  79,  81,
        84,  85,  89,  90,  92,  93,  95, 100, 111, 112, 115, 116, 120,
       121, 123, 124, 125, 126, 128, 129,   3,  10,  13,  15,  16,  23,
        31,  51,  71, 119], dtype=int64)

In [39]:
data_train.isna().sum()

Id                0
Province_State    0
Country_Region    0
Date              0
ConfirmedCases    0
Fatalities        0
dtype: int64

In [40]:
data_test.isna().sum()

ForecastId        0
Province_State    0
Country_Region    0
Date              0
dtype: int64

In [41]:
data_train.dtypes

Id                int64
Province_State    int32
Country_Region    int32
Date              int32
ConfirmedCases    int64
Fatalities        int64
dtype: object

In [42]:
data_test.dtypes

ForecastId        int64
Province_State    int32
Country_Region    int32
Date              int32
dtype: object

In [43]:
data_train

Id  Province_State  Country_Region  Date  ConfirmedCases  Fatalities
0          1              72               0   122               0           0
1          2              72               0   123               0           0
2          3              72               0   124               0           0
3          4              72               0   125               0           0
4          5              72               0   126               0           0
...      ...             ...             ...   ...             ...         ...
25035  35644              72             183   406              10           1
25036  35645              72             183   407              11           2
25037  35646              72             183   408              11           3
25038  35647              72             183   409              11           3
25039  35648              72             183   410              13           3

[25040 rows x 6 columns]

In [44]:
x_train = data_train[['Country_Region','Province_State','Date']].to_numpy()

In [45]:
y_train1 = data_train[['ConfirmedCases']].to_numpy()

In [46]:
y_train2 = data_train[['Fatalities']].to_numpy()

In [47]:
x_test = data_test[['Country_Region','Province_State','Date']].to_numpy()

In [48]:
y_train1=y_train1.reshape(-1)


In [49]:
y_train1

array([ 0,  0,  0, ..., 11, 11, 13], dtype=int64)

In [50]:
y_train2=y_train2.reshape(-1)


In [51]:
y_train2

array([0, 0, 0, ..., 3, 3, 3], dtype=int64)

In [52]:
#merge_data=pd.concat([data_train,data_test],keys=('train','test'))
#merge_data

In [53]:
#new_data=merge_data.drop(columns=['Id','ForecastId'])

In [54]:
#new_data

In [55]:
# Split train and test
#idx=pd.IndexSlice
#x_train=new_data.loc[idx[['train',],:]].to_numpy()
#x_test=new_data.loc[idx[['test',],:]].to_numpy()
#Now create a lable here only
#y_train1=data_train['ConfirmedCases'].to_numpy()
#y_train2=data_train['Fatalities'].to_numpy()
#print(x_train.shape)
#print(x_test.shape)

In [56]:
#from sklearn.model_selection import train_test_split

In [57]:
#x_train,x_test,y_train,y_test=train_test_split(x_train,y_train1, train_size=0.7 , test_size=0.3, random_state=100)

In [58]:
from statsmodels.api import OLS

In [59]:
def build_1model_model():
    model=LinearRegression()
    return model


In [60]:
model1=build_1model_model()
model1.fit(x_train,y_train1)
conf_pred=model1.predict(x_test)

In [61]:
conf_pred

array([2665.58780983, 2678.59884267, 2691.60987551, ..., 4148.40139191,
       4161.41242475, 4174.42345758])

In [62]:
model2=build_1model_model()
model2.fit(x_train,y_train2)
fatal_pred=model2.predict(x_test)

In [63]:
fatal_pred

array([139.01677805, 139.72860027, 140.44042248, ..., 223.99086533,
       224.70268754, 225.41450976])

In [64]:
df_out=pd.DataFrame({'ForecastId':[], 'confirmedcases':[],'fatalities': []})

In [65]:
test_Id=data_test.loc[:,'ForecastId']
df_ans=pd.DataFrame({'ForecastId':test_Id,'confirmedcases': conf_pred,'fatalities': fatal_pred})

df_out=pd.concat([df_out,df_ans],axis=0)

In [66]:
df_out.to_csv('submission.csv')

In [67]:
df_out.head()

ForecastId  confirmedcases  fatalities
0         1.0     2665.587810  139.016778
1         2.0     2678.598843  139.728600
2         3.0     2691.609876  140.440422
3         4.0     2704.620908  141.152245
4         5.0     2717.631941  141.864067

In [68]:
#print('Mean Absolute Error:',metrics.mean_absolute_error(x_test,model1))